name: DoGE
channels:
  - r
  - anaconda
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - aioeasywebdav=2.4.0
  - aiohttp=3.6.2
  - alsa-lib=1.1.5
  - appdirs=1.4.3
  - aria2=1.34.0
  - asn1crypto=1.3.0
  - async-timeout=3.0.1
  - attrs=19.3.0
  - bcrypt=3.1.7
  - binutils_impl_linux-64=2.34
  - binutils_linux-64=2.34
  - bioconductor-annotate=1.64.0
  - bioconductor-annotationdbi=1.48.0
  - bioconductor-biobase=2.46.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-delayedarray=0.12.0
  - bioconductor-deseq2=1.26.0
  - bioconductor-edger=3.28.0
  - bioconductor-genefilter=1.68.0
  - bioconductor-geneplotter=1.64.0
  - bioconductor-genomeinfodb=1.22.0
  - bioconductor-genomeinfodbdata=1.2.2
  - bioconductor-genomicranges=1.38.0
  - bioconductor-iranges=2.20.0
  - bioconductor-limma=3.42.0
  - bioconductor-s4vectors=0.24.0
  - bioconductor-summarizedexperiment=1.16.0
  - bioconductor-xvector=0.26.0
  - bioconductor-zlibbioc=1.32.0
  - boto3=1.12.30
  - botocore=1.15.31
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2020.4.5.1
  - cachetools=3.1.1
  - cairo=1.14.12
  - certifi=2020.4.5.1
  - cffi=1.14.0
  - chardet=3.0.4
  - click=7.1.1
  - colormath=3.0.0
  - configargparse=1.1
  - crc32c=2.0
  - cryptography=2.8
  - curl=7.68.0
  - cycler=0.10.0
  - datrie=0.8.2
  - dbus=1.13.12
  - decorator=4.4.2
  - dill=0.3.1.1
  - docutils=0.15.2
  - dropbox=9.4.0
  - expat=2.2.9
  - fastqc=0.11.9
  - fftw=3.3.8
  - filechunkio=1.8
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.0
  - fonts-conda-forge=1
  - freetype=2.10.1
  - fribidi=1.0.9
  - ftputil=3.4
  - future=0.18.2
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - ghostscript=9.22
  - giflib=5.2.1
  - gitdb=4.0.2
  - gitpython=3.1.0
  - glib=2.56.2
  - google-api-core=1.16.0
  - google-auth=1.12.0
  - google-cloud-core=1.3.0
  - google-cloud-storage=1.26.0
  - google-resumable-media=0.5.0
  - googleapis-common-protos=1.51.0
  - graphite2=1.3.13
  - graphviz=2.40.1
  - gsl=2.5
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=1.8.8
  - hisat2=2.2.0
  - icu=58.2
  - idna=2.9
  - idna_ssl=1.1.0
  - importlib-metadata=1.5.2
  - importlib_metadata=1.5.2
  - ipython_genutils=0.2.0
  - jbig=2.1
  - jinja2=2.11.1
  - jmespath=0.9.5
  - jpeg=9c
  - jsonschema=3.2.0
  - jupyter_core=4.6.3
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - lcms2=2.9
  - ld_impl_linux-64=2.34
  - libblas=3.8.0
  - libcblas=3.8.0
  - libclang=9.0.1
  - libcurl=7.68.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=9.2.0
  - libgfortran=3.0.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - libidn2=2.3.0
  - libjpeg-turbo=2.0.3
  - liblapack=3.8.0
  - libllvm9=9.0.1
  - libopenblas=0.3.9
  - libpng=1.6.37
  - libprotobuf=3.8.0
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libtool=2.4.6
  - libunistring=0.9.10
  - libuuid=1.0.3
  - libwebp=1.0.2
  - libxcb=1.13
  - libxkbcommon=0.10.0
  - libxml2=2.9.9
  - llvm-openmp=9.0.1
  - lz4-c=1.8.3
  - lzstring=1.0.4
  - make=4.3
  - markdown=3.2.1
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - multidict=4.7.5
  - multiprocess=0.70.9
  - multiqc=1.6
  - nbformat=5.0.4
  - ncurses=6.1
  - networkx=2.4
  - nspr=4.25
  - nss=3.47
  - numpy=1.18.1
  - openjdk=11.0.1
  - openjpeg=2.3.1
  - openssl=1.1.1f
  - pandas=1.0.3
  - pandoc=2.9.2.1
  - pango=1.42.4
  - paramiko=2.7.1
  - pcre=8.44
  - perl=5.26.2
  - pip=20.0.2
  - pixman=0.38.0
  - pkg-config=0.29.2
  - prettytable=0.7.2
  - protobuf=3.8.0
  - psutil=5.7.0
  - pthread-stubs=0.4
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.7
  - pycparser=2.20
  - pygments=2.6.1
  - pygraphviz=1.3.1
  - pynacl=1.3.0
  - pyopenssl=19.0.0
  - pyparsing=2.4.6
  - pyqt=5.9.2
  - pyrsistent=0.16.0
  - pysftp=0.2.9
  - pysocks=1.7.1
  - python=3.6.10
  - python-dateutil=2.8.1
  - python-irodsclient=0.8.2
  - python_abi=3.6
  - pytz=2019.3
  - pyyaml=5.3.1
  - qt=5.9.7
  - r-acepack=1.4.1
  - r-askpass=1.0
  - r-assertthat=0.2.1
  - r-backports=1.1.4
  - r-base=3.6.0
  - r-base64enc=0.1_3
  - r-bh=1.69.0_1
  - r-bit=1.1_14
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.1.1
  - r-calibrate=1.7.2
  - r-callr=3.2.0
  - r-catools=1.17.1.2
  - r-checkmate=1.9.1
  - r-cli=1.1.0
  - r-clipr=0.6.0
  - r-cluster=2.0.8
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-crayon=1.3.4
  - r-curl=3.3
  - r-data.table=1.12.2
  - r-dbi=1.0.0
  - r-dichromat=2.0_0
  - r-digest=0.6.18
  - r-doparallel=1.0.14
  - r-dplyr=0.8.0.1
  - r-evaluate=0.13
  - r-fansi=0.4.0
  - r-foreach=1.4.4
  - r-foreign=0.8_71
  - r-formatr=1.6
  - r-formula=1.2_3
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-gdata=2.18.0
  - r-ggally=1.5.0
  - r-ggplot2=3.3.0
  - r-ggrepel=0.8.2
  - r-glue=1.3.1
  - r-gplots=3.0.1.1
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-gtools=3.8.1
  - r-highr=0.8
  - r-hmisc=4.2_0
  - r-hms=0.4.2
  - r-htmltable=1.13.1
  - r-htmltools=0.3.6
  - r-htmlwidgets=1.3
  - r-httr=1.4.0
  - r-isoband=0.2.0
  - r-iterators=1.0.10
  - r-jsonlite=1.6
  - r-kableextra=1.1.0
  - r-kernsmooth=2.23_15
  - r-knitr=1.22
  - r-labeling=0.3
  - r-lambda.r=1.2.3
  - r-latex2exp=0.4.0
  - r-lattice=0.20_38
  - r-latticeextra=0.6_28
  - r-locfit=1.5_9.4
  - r-magrittr=1.5
  - r-markdown=0.9
  - r-mass=7.3_51.3
  - r-matrix=1.2_17
  - r-matrixstats=0.54.0
  - r-memoise=1.1.0
  - r-mgcv=1.8_28
  - r-mime=0.6
  - r-munsell=0.5.0
  - r-nlme=3.1_139
  - r-nnet=7.3_12
  - r-openssl=1.3
  - r-pander=0.6.3
  - r-pillar=1.3.1
  - r-pkgconfig=2.0.2
  - r-plogr=0.2.0
  - r-plyr=1.8.4
  - r-png=0.1_7
  - r-praise=1.0.0
  - r-prettyunits=1.0.2
  - r-processx=3.3.0
  - r-progress=1.2.0
  - r-ps=1.3.0
  - r-purrr=0.3.2
  - r-r6=2.4.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.1
  - r-rcpparmadillo=0.9.300.2.0
  - r-rcurl=1.95_4.12
  - r-readr=1.3.1
  - r-reshape=0.8.8
  - r-rlang=0.3.4
  - r-rmarkdown=1.12
  - r-rpart=4.1_15
  - r-rsqlite=2.1.1
  - r-rstudioapi=0.10
  - r-rvest=0.3.3
  - r-scales=1.0.0
  - r-selectr=0.4_1
  - r-snow=0.4_3
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=2.44_1.1
  - r-sys=3.2
  - r-testthat=2.1.1
  - r-tibble=2.1.1
  - r-tictoc=1.0
  - r-tidyselect=0.2.5
  - r-tinytex=0.12
  - r-utf8=1.1.4
  - r-viridis=0.5.1
  - r-viridislite=0.3.0
  - r-webshot=0.5.1
  - r-withr=2.1.2
  - r-xfun=0.6
  - r-xml=3.98_1.19
  - r-xml2=1.2.0
  - r-xtable=1.8_4
  - r-yaml=2.2.0
  - ratelimiter=1.2.0
  - readline=7.0
  - requests=2.23.0
  - rsa=4.0
  - s3transfer=0.3.3
  - samstats=0.2.2
  - samtools=1.3.1
  - setuptools=46.1.3
  - simplejson=3.17.0
  - sip=4.19.20
  - six=1.14.0
  - smmap=3.0.1
  - snakemake=4.3.0
  - snakemake-minimal=5.13.0
  - spectra=0.0.11
  - sqlite=3.31.1
  - subread=2.0.0
  - tk=8.6.10
  - tktable=2.10
  - toposort=1.5
  - tornado=6.0.4
  - traitlets=4.3.3
  - trimmomatic=0.39
  - typing_extensions=3.7.4.1
  - urllib3=1.25.7
  - wget=1.20.1
  - wheel=0.34.2
  - wrapt=1.12.1
  - xmlrunner=1.7.7
  - xorg-fixesproto=5.0
  - xorg-inputproto=2.3.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxfixes=5.0.3
  - xorg-libxi=1.7.10
  - xorg-libxrender=0.9.10
  - xorg-libxtst=1.2.3
  - xorg-recordproto=1.14.2
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - yaml=0.2.2
  - yarl=1.3.0
  - zipp=3.1.0
  - zlib=1.2.11
  - zstd=1.4.4

